"""Tests for post-build cleanup of the generated mkdocs.yml."""

from __future__ import annotations

import os
import textwrap
from types import SimpleNamespace

import pytest

from repoquill.cli import _cleanup_mkdocs_yml, _mkdocs_cwd, _run_mkdocs_build


def _cfg(tmp_path, output_dir=None):
    """Build a minimal config object for cleanup/build tests."""
    raw = {}
    if output_dir:
        raw["output_dir"] = output_dir
    docs_dir = "docs"
    if output_dir:
        site_src = str(tmp_path / output_dir)
    else:
        site_src = str(tmp_path / docs_dir)
    return SimpleNamespace(
        raw=raw,
        site_src=site_src,
        config_dir=str(tmp_path),
        build={"docs_dir": docs_dir, "site_dir": "docs/site"},
    )


def test_cleanup_removes_generated_mkdocs_yml(tmp_path):
    cfg = _cfg(tmp_path)
    mkdocs = os.path.join(_mkdocs_cwd(cfg), "mkdocs.yml")
    with open(mkdocs, "w") as f:
        f.write("# Generated by repoquill — DO NOT EDIT by hand.\nsite_name: x\n")
    _cleanup_mkdocs_yml(cfg)
    assert not os.path.exists(mkdocs)


def test_cleanup_preserves_handwritten_mkdocs_yml(tmp_path):
    cfg = _cfg(tmp_path)
    mkdocs = os.path.join(_mkdocs_cwd(cfg), "mkdocs.yml")
    with open(mkdocs, "w") as f:
        f.write("site_name: mine\n")
    _cleanup_mkdocs_yml(cfg)
    assert os.path.exists(mkdocs)


def test_cleanup_missing_file_is_noop(tmp_path):
    cfg = _cfg(tmp_path)
    _cleanup_mkdocs_yml(cfg)  # must not raise


def test_cleanup_output_dir_mode(tmp_path):
    """With output_dir, mkdocs.yml lives inside site_src and is removed there."""
    cfg = _cfg(tmp_path, output_dir="docs")
    mkdocs = os.path.join(_mkdocs_cwd(cfg), "mkdocs.yml")
    os.makedirs(os.path.dirname(mkdocs), exist_ok=True)
    with open(mkdocs, "w") as f:
        f.write("# Generated by repoquill — DO NOT EDIT by hand.\nsite_name: x\n")
    _cleanup_mkdocs_yml(cfg)
    assert not os.path.exists(mkdocs)


def test_run_mkdocs_build_cleans_up(tmp_path, monkeypatch):
    """After a successful build, the generated mkdocs.yml is removed."""
    cfg = _cfg(tmp_path)
    mkdocs = os.path.join(_mkdocs_cwd(cfg), "mkdocs.yml")
    with open(mkdocs, "w") as f:
        f.write("# Generated by repoquill — DO NOT EDIT by hand.\nsite_name: x\n")

    calls = []

    def fake_run(cmd, **kw):
        calls.append((cmd, kw))
        # Simulate mkdocs producing a docs/site/ dir
        site = os.path.join(kw["cwd"], "docs", "site")
        os.makedirs(site, exist_ok=True)

    monkeypatch.setattr("repoquill.cli.subprocess.run", fake_run)
    _run_mkdocs_build(cfg)
    assert calls, "mkdocs build was not invoked"
    assert not os.path.exists(mkdocs)


def test_run_mkdocs_build_failure_keeps_mkdocs_yml(tmp_path, monkeypatch):
    """If the build fails, mkdocs.yml is kept (for debugging)."""
    cfg = _cfg(tmp_path)
    mkdocs = os.path.join(_mkdocs_cwd(cfg), "mkdocs.yml")
    with open(mkdocs, "w") as f:
        f.write("# Generated by repoquill — DO NOT EDIT by hand.\nsite_name: x\n")

    def fake_run(cmd, **kw):
        raise RuntimeError("mkdocs build failed")

    monkeypatch.setattr("repoquill.cli.subprocess.run", fake_run)
    with pytest.raises(RuntimeError):
        _run_mkdocs_build(cfg)
    assert os.path.exists(mkdocs)
